INSERT INTO shop (name, address, working_hours) VALUES ('A Corua (La Corua)', '47 MySakila Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Abha', '28 MySQL Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Abu Dhabi', '23 Workhaven Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Acua', '1411 Lillydale Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Adana', '1913 Hanoi Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Addis Abeba', '1121 Loja Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Aden', '692 Joliet Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Adoni', '1566 Inegl Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ahmadnagar', '53 Idfu Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Akishima', '1795 Santiago de Compostela', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Akron', '900 Santiago de Compostela', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('al-Ayn', '478 Joliet Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('al-Hawiya', '613 Korolev Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('al-Manama', '1531 Sal Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('al-Qadarif', '1542 Tarlac Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('al-Qatif', '808 Bhopal Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Alessandria', '270 Amroha Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Allappuzha (Alleppey)', '770 Bydgoszcz Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Allende', '419 Iligan Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Almirante Brown', '360 Toulouse Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Alvorada', '270 Toulon Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ambattur', '320 Brest Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Amersfoort', '1417 Lancaster Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Amroha', '1688 Okara Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Angra dos Reis', '262 A Corua', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Anpolis', '28 Charlotte Amalie Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Antofagasta', '1780 Hino Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Aparecida de Goinia', '96 Tafuna Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Apeldoorn', '934 San Felipe', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Araatuba', '18 Duisburg Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Arak', '217 Botshabelo Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Arecibo', '1425 Shikarpur Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Arlington', '786 Aurora Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ashdod', '1668 Anpolis Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ashgabat', '33 Gorontalo Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ashqelon', '176 Mandaluyong Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Asuncin', '127 Purnea (Purnia)', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Athenai', '61 Tama Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Atinsk', '391 Callao Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Atlixco', '334 Munger (Monghyr)', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Augusta-Richmond County', '1440 Fukuyama Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Aurora', '269 Cam Ranh Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Avellaneda', '306 Antofagasta Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bag', '671 Graz Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Baha Blanca', '42 Brindisi Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Baicheng', '1632 Bislig Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Baiyin', '1447 Imus Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Baku', '1998 Halifax Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Balaiha', '1718 Valencia Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Balikesir', '46 Pjatigorsk Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Balurghat', '686 Garland Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bamenda', '909 Garland Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bandar Seri Begawan', '725 Isesaki Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Banjul', '115 Hidalgo Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Barcelona', '1135 Izumisano Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Basel', '939 Probolinggo Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bat Yam', '17 Kabul Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Batman', '1964 Allappuzha (Alleppey)', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Batna', '1697 Kowloon and New', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Battambang', '1668 Saint Louis Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Baybay', '943 Tokat Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bayugan', '1114 Liepaja Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bchar', '1213 Ranchi Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Beira', '81 Hodeida Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bellevue', '915 Ponce Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Belm', '1717 Guadalajara Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Benguela', '1214 Hanoi Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Beni-Mellal', '1966 Amroha Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Benin City', '698 Otsu Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bergamo', '1150 Kimchon Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Berhampore (Baharampur)', '1586 Guaruj Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bern', '57 Arlington Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bhavnagar', '1031 Daugavpils Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bhilwara', '1124 Buenaventura Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bhimavaram', '492 Cam Ranh Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bhopal', '89 Allappuzha (Alleppey)', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bhusawal', '1947 Poos de Caldas', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bijapur', '1206 Dos Quebradas Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bilbays', '1551 Rampur Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Binzhou', '602 Paarl Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Birgunj', '1692 Ede Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bislig', '936 Salzburg Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Blumenau', '586 Tete Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Boa Vista', '1888 Kabul Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Boksburg', '320 Baiyin Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Botosani', '927 Baha Blanca Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Botshabelo', '929 Tallahassee Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bradford', '125 Citt del Vaticano', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Braslia', '1557 Ktahya Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bratislava', '870 Ashqelon Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Brescia', '1740 Portoviejo Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Brest', '1942 Ciparay Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Brindisi', '1926 El Alto Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Brockton', '1952 Chatsworth Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bucuresti', '1370 Le Mans Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Buenaventura', '984 Effon-Alaiye Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Bydgoszcz', '832 Nakhon Sawan Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cabuyao', '152 Kitwe Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Callao', '1697 Tanauan Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cam Ranh', '1308 Arecibo Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cape Coral', '1599 Plock Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Caracas', '669 Firozabad Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Carmen', '588 Vila Velha Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cavite', '1913 Kamakura Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cayenne', '733 Mandaluyong Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Celaya', '659 Vaduz Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Chandrapur', '1177 Jelets Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Changhwa', '1386 Yangor Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Changzhou', '454 Nakhon Sawan Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Chapra', '1867 San Juan Bautista', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Charlotte Amalie', '1532 Dzerzinsk Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Chatsworth', '1002 Ahmadnagar Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cheju', '682 Junan Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Chiayi', '804 Elista Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Chisinau', '1378 Alvorada Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Chungho', '793 Cam Ranh Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cianjur', '1079 Tel Aviv-Jaffa', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ciomas', '442 Rae Bareli Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ciparay', '1107 Nakhon Sawan Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Citrus Heights', '544 Malm Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Citt del Vaticano', '1967 Sincelejo Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ciudad del Este', '333 Goinia Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Clarksville', '1987 Coacalco de Berriozbal', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Coacalco de Berriozbal', '241 Mosul Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Coatzacoalcos', '211 Chiayi Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Compton', '1175 Tanauan Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Coquimbo', '117 Boa Vista Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Crdoba', '848 Tafuna Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cuauhtmoc', '569 Baicheng Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cuautla', '1666 Qomsheh Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cuernavaca', '801 Hagonoy Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Cuman', '1050 Garden Grove Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Czestochowa', '1854 Tieli Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dadu', '758 Junan Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dallas', '1752 So Leopoldo Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Datong', '898 Belm Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Daugavpils', '261 Saint Louis Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Davao', '765 Southampton Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Daxian', '943 Johannesburg Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dayton', '788 Atinsk Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Deba Habe', '1749 Daxian Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Denizli', '1587 Sullana Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dhaka', '1029 Dzerzinsk Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dhule (Dhulia)', '1666 Beni-Mellal Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dongying', '928 Jaffna Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Donostia-San Sebastin', '483 Ljubertsy Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dos Quebradas', '374 Bat Yam Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Duisburg', '1027 Songkhla Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dundee', '999 Sanaa Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Dzerzinsk', '879 Newcastle Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ede', '1337 Lincoln Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Effon-Alaiye', '1952 Pune Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('El Alto', '782 Mosul Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('El Fuerte', '781 Shimonoseki Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('El Monte', '1560 Jelets Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Elista', '1963 Moscow Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Emeishan', '456 Escobar Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Emmen', '798 Cianjur Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Enshi', '185 Novi Sad Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Erlangen', '1367 Yantai Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Escobar', '1386 Nakhon Sawan Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Esfahan', '369 Papeete Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Eskisehir', '1440 Compton Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Etawah', '1623 Baha Blanca Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ezeiza', '97 Shimoga Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Ezhou', '1740 Le Mans Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Faaa', '1287 Xiangfan Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Fengshan', '842 Salzburg Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Firozabad', '154 Tallahassee Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Florencia', '710 San Felipe del', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Fontana', '1540 Wroclaw Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Fukuyama', '475 Atinsk Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Funafuti', '1294 Firozabad Drive', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Fuyu', '1877 Ezhou Lane', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Fuzhou', '316 Uruapan Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gandhinagar', '29 Pyongyang Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Garden Grove', '1010 Klerksdorp Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Garland', '1848 Salala Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gatineau', '431 Xiangtan Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gaziantep', '757 Rustenburg Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gijn', '146 Johannesburg Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gingoog', '1891 Rizhao Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Goinia', '1089 Iwatsuki Avenue', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gorontalo', '1410 Benin City Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Grand Prairie', '682 Garden Grove Place', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Graz', '533 al-Ayn Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Greensboro', '1839 Szkesfehrvr Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Guadalajara', '741 Ambattur Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Guaruj', '927 Barcelona Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('guas Lindas de Gois', '435 0 Way', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Gulbarga', '140 Chiayi Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Hagonoy', '1166 Changhwa Street', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Haining', '891 Novi Sad Manor', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Haiphong', '605 Rio Claro Parkway', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Haldia', '1077 San Felipe', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Halifax', '9 San Miguel', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Halisahar', '447 Surakarta Loop', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Halle/Saale', '345 Oshawa Boulevard', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Hami', '1792 Valle', '08.00-20.00');
INSERT INTO shop (name, address, working_hours) VALUES ('Hamilton', '1074 Binzhou Manor', '08.00-20.00');

INSERT INTO product (name, description) VALUES ('ACADEMY DINOSAUR','A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('ACE GOLDFINGER','A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China');
INSERT INTO product (name, description) VALUES ('ADAPTATION HOLES','A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory');
INSERT INTO product (name, description) VALUES ('AFFAIR PREJUDICE','A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank');
INSERT INTO product (name, description) VALUES ('AFRICAN EGG','A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico');
INSERT INTO product (name, description) VALUES ('AGENT TRUMAN','A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China');
INSERT INTO product (name, description) VALUES ('AIRPLANE SIERRA','A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat');
INSERT INTO product (name, description) VALUES ('AIRPORT POLLOCK','A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India');
INSERT INTO product (name, description) VALUES ('ALABAMA DEVIL','A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat');
INSERT INTO product (name, description) VALUES ('ALADDIN CALENDAR','A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China');
INSERT INTO product (name, description) VALUES ('ALAMO VIDEOTAPE','A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('ALASKA PHANTOM','A Fanciful Saga of a Hunter And a Pastry Chef who must Vanquish a Boy in Australia');
INSERT INTO product (name, description) VALUES ('ALI FOREVER','A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('ALICE FANTASIA','A Emotional Drama of a A Shark And a Database Administrator who must Vanquish a Pioneer in Soviet Georgia');
INSERT INTO product (name, description) VALUES ('ALIEN CENTER','A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('ALLEY EVOLUTION','A Fast-Paced Drama of a Robot And a Composer who must Battle a Astronaut in New Orleans');
INSERT INTO product (name, description) VALUES ('ALONE TRIP','A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('ALTER VICTORY','A Thoughtful Drama of a Composer And a Feminist who must Meet a Secret Agent in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('AMADEUS HOLY','A Emotional Display of a Pioneer And a Technical Writer who must Battle a Man in A Baloon');
INSERT INTO product (name, description) VALUES ('AMELIE HELLFIGHTERS','A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon');
INSERT INTO product (name, description) VALUES ('AMERICAN CIRCUS','A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank');
INSERT INTO product (name, description) VALUES ('AMISTAD MIDSUMMER','A Emotional Character Study of a Dentist And a Crocodile who must Meet a Sumo Wrestler in California');
INSERT INTO product (name, description) VALUES ('ANACONDA CONFESSIONS','A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia');
INSERT INTO product (name, description) VALUES ('ANALYZE HOOSIERS','A Thoughtful Display of a Explorer And a Pastry Chef who must Overcome a Feminist in The Sahara Desert');
INSERT INTO product (name, description) VALUES ('ANGELS LIFE','A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin');
INSERT INTO product (name, description) VALUES ('ANNIE IDENTITY','A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('ANONYMOUS HUMAN','A Amazing Reflection of a Database Administrator And a Astronaut who must Outrace a Database Administrator in A Shark Tank');
INSERT INTO product (name, description) VALUES ('ANTHEM LUKE','A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('ANTITRUST TOMATOES','A Fateful Yarn of a Womanizer And a Feminist who must Succumb a Database Administrator in Ancient India');
INSERT INTO product (name, description) VALUES ('ANYTHING SAVANNAH','A Epic Story of a Pastry Chef And a Woman who must Chase a Feminist in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('APACHE DIVINE','A Awe-Inspiring Reflection of a Pastry Chef And a Teacher who must Overcome a Sumo Wrestler in A U-Boat');
INSERT INTO product (name, description) VALUES ('APOCALYPSE FLAMINGOS','A Astounding Story of a Dog And a Squirrel who must Defeat a Woman in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('APOLLO TEEN','A Action-Packed Reflection of a Crocodile And a Explorer who must Find a Sumo Wrestler in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('ARABIA DOGMA','A Touching Epistle of a Madman And a Mad Cow who must Defeat a Student in Nigeria');
INSERT INTO product (name, description) VALUES ('ARACHNOPHOBIA ROLLERCOASTER','A Action-Packed Reflection of a Pastry Chef And a Composer who must Discover a Mad Scientist in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('ARGONAUTS TOWN','A Emotional Epistle of a Forensic Psychologist And a Butler who must Challenge a Waitress in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('ARIZONA BANG','A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery');
INSERT INTO product (name, description) VALUES ('ARK RIDGEMONT','A Beautiful Yarn of a Pioneer And a Monkey who must Pursue a Explorer in The Sahara Desert');
INSERT INTO product (name, description) VALUES ('ARMAGEDDON LOST','A Fast-Paced Tale of a Boat And a Teacher who must Succumb a Composer in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('ARMY FLINTSTONES','A Boring Saga of a Database Administrator And a Womanizer who must Battle a Waitress in Nigeria');
INSERT INTO product (name, description) VALUES ('ARSENIC INDEPENDENCE','A Fanciful Documentary of a Mad Cow And a Womanizer who must Find a Dentist in Berlin');
INSERT INTO product (name, description) VALUES ('ARTIST COLDBLOODED','A Stunning Reflection of a Robot And a Moose who must Challenge a Woman in California');
INSERT INTO product (name, description) VALUES ('ATLANTIS CAUSE','A Thrilling Yarn of a Feminist And a Hunter who must Fight a Technical Writer in A Shark Tank');
INSERT INTO product (name, description) VALUES ('ATTACKS HATE','A Fast-Paced Panorama of a Technical Writer And a Mad Scientist who must Find a Feminist in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('ATTRACTION NEWTON','A Astounding Panorama of a Composer And a Frisbee who must Reach a Husband in Ancient Japan');
INSERT INTO product (name, description) VALUES ('AUTUMN CROW','A Beautiful Tale of a Dentist And a Mad Cow who must Battle a Moose in The Sahara Desert');
INSERT INTO product (name, description) VALUES ('BABY HALL','A Boring Character Study of a A Shark And a Girl who must Outrace a Feminist in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('BACKLASH UNDEFEATED','A Stunning Character Study of a Mad Scientist And a Mad Cow who must Kill a Car in A Monastery');
INSERT INTO product (name, description) VALUES ('BADMAN DAWN','A Emotional Panorama of a Pioneer And a Composer who must Escape a Mad Scientist in A Jet Boat');
INSERT INTO product (name, description) VALUES ('BAKED CLEOPATRA','A Stunning Drama of a Forensic Psychologist And a Husband who must Overcome a Waitress in A Monastery');
INSERT INTO product (name, description) VALUES ('BALLOON HOMEWARD','A Insightful Panorama of a Forensic Psychologist And a Mad Cow who must Build a Mad Scientist in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BALLROOM MOCKINGBIRD','A Thrilling Documentary of a Composer And a Monkey who must Find a Feminist in California');
INSERT INTO product (name, description) VALUES ('BANG KWAI','A Epic Drama of a Madman And a Cat who must Face a A Shark in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('BANGER PINOCCHIO','A Awe-Inspiring Drama of a Car And a Pastry Chef who must Chase a Crocodile in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BARBARELLA STREETCAR','A Awe-Inspiring Story of a Feminist And a Cat who must Conquer a Dog in A Monastery');
INSERT INTO product (name, description) VALUES ('BAREFOOT MANCHURIAN','A Intrepid Story of a Cat And a Student who must Vanquish a Girl in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('BASIC EASY','A Stunning Epistle of a Man And a Husband who must Reach a Mad Scientist in A Jet Boat');
INSERT INTO product (name, description) VALUES ('BEACH HEARTBREAKERS','A Fateful Display of a Womanizer And a Mad Scientist who must Outgun a A Shark in Soviet Georgia');
INSERT INTO product (name, description) VALUES ('BEAR GRACELAND','A Astounding Saga of a Dog And a Boy who must Kill a Teacher in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BEAST HUNCHBACK','A Awe-Inspiring Epistle of a Student And a Squirrel who must Defeat a Boy in Ancient China');
INSERT INTO product (name, description) VALUES ('BEAUTY GREASE','A Fast-Paced Display of a Composer And a Moose who must Sink a Robot in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('BED HIGHBALL','A Astounding Panorama of a Lumberjack And a Dog who must Redeem a Woman in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('BEDAZZLED MARRIED','A Astounding Character Study of a Madman And a Robot who must Meet a Mad Scientist in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('BEETHOVEN EXORCIST','A Epic Display of a Pioneer And a Student who must Challenge a Butler in The Gulf of Mexico');
INSERT INTO product (name, description) VALUES ('BEHAVIOR RUNAWAY','A Unbelieveable Drama of a Student And a Husband who must Outrace a Sumo Wrestler in Berlin');
INSERT INTO product (name, description) VALUES ('BENEATH RUSH','A Astounding Panorama of a Man And a Monkey who must Discover a Man in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BERETS AGENT','A Taut Saga of a Crocodile And a Boy who must Overcome a Technical Writer in Ancient China');
INSERT INTO product (name, description) VALUES ('BETRAYED REAR','A Emotional Character Study of a Boat And a Pioneer who must Find a Explorer in A Shark Tank');
INSERT INTO product (name, description) VALUES ('BEVERLY OUTLAW','A Fanciful Documentary of a Womanizer And a Boat who must Defeat a Madman in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BIKINI BORROWERS','A Astounding Drama of a Astronaut And a Cat who must Discover a Woman in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BILKO ANONYMOUS','A Emotional Reflection of a Teacher And a Man who must Meet a Cat in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BILL OTHERS','A Stunning Saga of a Mad Scientist And a Forensic Psychologist who must Challenge a Squirrel in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('BINGO TALENTED','A Touching Tale of a Girl And a Crocodile who must Discover a Waitress in Nigeria');
INSERT INTO product (name, description) VALUES ('BIRCH ANTITRUST','A Fanciful Panorama of a Husband And a Pioneer who must Outgun a Dog in A Baloon');
INSERT INTO product (name, description) VALUES ('BIRD INDEPENDENCE','A Thrilling Documentary of a Car And a Student who must Sink a Hunter in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('BIRDCAGE CASPER','A Fast-Paced Saga of a Frisbee And a Astronaut who must Overcome a Feminist in Ancient India');
INSERT INTO product (name, description) VALUES ('BIRDS PERDITION','A Boring Story of a Womanizer And a Pioneer who must Face a Dog in California');
INSERT INTO product (name, description) VALUES ('BLACKOUT PRIVATE','A Intrepid Yarn of a Pastry Chef And a Mad Scientist who must Challenge a Secret Agent in Ancient Japan');
INSERT INTO product (name, description) VALUES ('BLADE POLISH','A Thoughtful Character Study of a Frisbee And a Pastry Chef who must Fight a Dentist in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BLANKET BEVERLY','A Emotional Documentary of a Student And a Girl who must Build a Boat in Nigeria');
INSERT INTO product (name, description) VALUES ('BLINDNESS GUN','A Touching Drama of a Robot And a Dentist who must Meet a Hunter in A Jet Boat');
INSERT INTO product (name, description) VALUES ('BLOOD ARGONAUTS','A Boring Drama of a Explorer And a Man who must Kill a Lumberjack in A Manhattan Penthouse');
INSERT INTO product (name, description) VALUES ('BLUES INSTINCT','A Insightful Documentary of a Boat And a Composer who must Meet a Forensic Psychologist in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('BOILED DARES','A Awe-Inspiring Story of a Waitress And a Dog who must Discover a Dentist in Ancient Japan');
INSERT INTO product (name, description) VALUES ('BONNIE HOLOCAUST','A Fast-Paced Story of a Crocodile And a Robot who must Find a Moose in Ancient Japan');
INSERT INTO product (name, description) VALUES ('BOOGIE AMELIE','A Lacklusture Character Study of a Husband And a Sumo Wrestler who must Succumb a Technical Writer in The Gulf of Mexico');
INSERT INTO product (name, description) VALUES ('BOONDOCK BALLROOM','A Fateful Panorama of a Crocodile And a Boy who must Defeat a Monkey in The Gulf of Mexico');
INSERT INTO product (name, description) VALUES ('BORN SPINAL','A Touching Epistle of a Frisbee And a Husband who must Pursue a Student in Nigeria');
INSERT INTO product (name, description) VALUES ('BORROWERS BEDAZZLED','A Brilliant Epistle of a Teacher And a Sumo Wrestler who must Defeat a Man in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('BOULEVARD MOB','A Fateful Epistle of a Moose And a Monkey who must Confront a Lumberjack in Ancient China');
INSERT INTO product (name, description) VALUES ('BOUND CHEAPER','A Thrilling Panorama of a Database Administrator And a Astronaut who must Challenge a Lumberjack in A Baloon');
INSERT INTO product (name, description) VALUES ('BOWFINGER GABLES','A Fast-Paced Yarn of a Waitress And a Composer who must Outgun a Dentist in California');
INSERT INTO product (name, description) VALUES ('BRANNIGAN SUNRISE','A Amazing Epistle of a Moose And a Crocodile who must Outrace a Dog in Berlin');
INSERT INTO product (name, description) VALUES ('BRAVEHEART HUMAN','A Insightful Story of a Dog And a Pastry Chef who must Battle a Girl in Berlin');
INSERT INTO product (name, description) VALUES ('BREAKFAST GOLDFINGER','A Beautiful Reflection of a Student And a Student who must Fight a Moose in Berlin');
INSERT INTO product (name, description) VALUES ('BREAKING HOME','A Beautiful Display of a Secret Agent And a Monkey who must Battle a Sumo Wrestler in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('BRIDE INTRIGUE','A Epic Tale of a Robot And a Monkey who must Vanquish a Man in New Orleans');
INSERT INTO product (name, description) VALUES ('BRIGHT ENCOUNTERS','A Fateful Yarn of a Lumberjack And a Feminist who must Conquer a Student in A Jet Boat');
INSERT INTO product (name, description) VALUES ('BRINGING HYSTERICAL','A Fateful Saga of a A Shark And a Technical Writer who must Find a Woman in A Jet Boat');
INSERT INTO product (name, description) VALUES ('BROOKLYN DESERT','A Beautiful Drama of a Dentist And a Composer who must Battle a Sumo Wrestler in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BROTHERHOOD BLANKET','A Fateful Character Study of a Butler And a Technical Writer who must Sink a Astronaut in Ancient Japan');
INSERT INTO product (name, description) VALUES ('BUBBLE GROSSE','A Awe-Inspiring Panorama of a Crocodile And a Moose who must Confront a Girl in A Baloon');
INSERT INTO product (name, description) VALUES ('BUCKET BROTHERHOOD','A Amazing Display of a Girl And a Womanizer who must Succumb a Lumberjack in A Baloon Factory');
INSERT INTO product (name, description) VALUES ('BUGSY SONG','A Awe-Inspiring Character Study of a Secret Agent And a Boat who must Find a Squirrel in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('BULL SHAWSHANK','A Fanciful Drama of a Moose And a Squirrel who must Conquer a Pioneer in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('BULWORTH COMMANDMENTS','A Amazing Display of a Mad Cow And a Pioneer who must Redeem a Sumo Wrestler in The Outback');
INSERT INTO product (name, description) VALUES ('BUNCH MINDS','A Emotional Story of a Feminist And a Feminist who must Escape a Pastry Chef in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('BUTCH PANTHER','A Lacklusture Yarn of a Feminist And a Database Administrator who must Face a Hunter in New Orleans');
INSERT INTO product (name, description) VALUES ('BUTTERFLY CHOCOLAT','A Fateful Story of a Girl And a Composer who must Conquer a Husband in A Shark Tank');
INSERT INTO product (name, description) VALUES ('CABIN FLASH','A Stunning Epistle of a Boat And a Man who must Challenge a A Shark in A Baloon Factory');
INSERT INTO product (name, description) VALUES ('CADDYSHACK JEDI','A Awe-Inspiring Epistle of a Woman And a Madman who must Fight a Robot in Soviet Georgia');
INSERT INTO product (name, description) VALUES ('CALENDAR GUNFIGHT','A Thrilling Drama of a Frisbee And a Lumberjack who must Sink a Man in Nigeria');
INSERT INTO product (name, description) VALUES ('CALIFORNIA BIRDS','A Thrilling Yarn of a Database Administrator And a Robot who must Battle a Database Administrator in Ancient India');
INSERT INTO product (name, description) VALUES ('CAMELOT VACATION','A Touching Character Study of a Woman And a Waitress who must Battle a Pastry Chef in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('CAMPUS REMEMBER','A Astounding Drama of a Crocodile And a Mad Cow who must Build a Robot in A Jet Boat');
INSERT INTO product (name, description) VALUES ('CANDIDATE PERDITION','A Brilliant Epistle of a Composer And a Database Administrator who must Vanquish a Mad Scientist in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('CANDLES GRAPES','A Fanciful Character Study of a Monkey And a Explorer who must Build a Astronaut in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('CANYON STOCK','A Thoughtful Reflection of a Waitress And a Feminist who must Escape a Squirrel in A Manhattan Penthouse');
INSERT INTO product (name, description) VALUES ('CAPER MOTIONS','A Fateful Saga of a Moose And a Car who must Pursue a Woman in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('CARIBBEAN LIBERTY','A Fanciful Tale of a Pioneer And a Technical Writer who must Outgun a Pioneer in A Shark Tank');
INSERT INTO product (name, description) VALUES ('CAROL TEXAS','A Astounding Character Study of a Composer And a Student who must Overcome a Composer in A Monastery');
INSERT INTO product (name, description) VALUES ('CARRIE BUNCH','A Amazing Epistle of a Student And a Astronaut who must Discover a Frisbee in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('CASABLANCA SUPER','A Amazing Panorama of a Crocodile And a Forensic Psychologist who must Pursue a Secret Agent in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('CASPER DRAGONFLY','A Intrepid Documentary of a Boat And a Crocodile who must Chase a Robot in The Sahara Desert');
INSERT INTO product (name, description) VALUES ('CASSIDY WYOMING','A Intrepid Drama of a Frisbee And a Hunter who must Kill a Secret Agent in New Orleans');
INSERT INTO product (name, description) VALUES ('CASUALTIES ENCINO','A Insightful Yarn of a A Shark And a Pastry Chef who must Face a Boy in A Monastery');
INSERT INTO product (name, description) VALUES ('CAT CONEHEADS','A Fast-Paced Panorama of a Girl And a A Shark who must Confront a Boy in Ancient India');
INSERT INTO product (name, description) VALUES ('CATCH AMISTAD','A Boring Reflection of a Lumberjack And a Feminist who must Discover a Woman in Nigeria');
INSERT INTO product (name, description) VALUES ('CAUSE DATE','A Taut Tale of a Explorer And a Pastry Chef who must Conquer a Hunter in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('CELEBRITY HORN','A Amazing Documentary of a Secret Agent And a Astronaut who must Vanquish a Hunter in A Shark Tank');
INSERT INTO product (name, description) VALUES ('CENTER DINOSAUR','A Beautiful Character Study of a Sumo Wrestler And a Dentist who must Find a Dog in California');
INSERT INTO product (name, description) VALUES ('CHAINSAW UPTOWN','A Beautiful Documentary of a Boy And a Robot who must Discover a Squirrel in Australia');
INSERT INTO product (name, description) VALUES ('CHAMBER ITALIAN','A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria');
INSERT INTO product (name, description) VALUES ('CHAMPION FLATLINERS','A Amazing Story of a Mad Cow And a Dog who must Kill a Husband in A Monastery');
INSERT INTO product (name, description) VALUES ('CHANCE RESURRECTION','A Astounding Story of a Forensic Psychologist And a Forensic Psychologist who must Overcome a Moose in Ancient China');
INSERT INTO product (name, description) VALUES ('CHAPLIN LICENSE','A Boring Drama of a Dog And a Forensic Psychologist who must Outrace a Explorer in Ancient India');
INSERT INTO product (name, description) VALUES ('CHARADE DUFFEL','A Action-Packed Display of a Man And a Waitress who must Build a Dog in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('CHARIOTS CONSPIRACY','A Unbelieveable Epistle of a Robot And a Husband who must Chase a Robot in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('CHASING FIGHT','A Astounding Saga of a Technical Writer And a Butler who must Battle a Butler in A Shark Tank');
INSERT INTO product (name, description) VALUES ('CHEAPER CLYDE','A Emotional Character Study of a Pioneer And a Girl who must Discover a Dog in Ancient Japan');
INSERT INTO product (name, description) VALUES ('CHICAGO NORTH','A Fateful Yarn of a Mad Cow And a Waitress who must Battle a Student in California');
INSERT INTO product (name, description) VALUES ('CHICKEN HELLFIGHTERS','A Emotional Drama of a Dog And a Explorer who must Outrace a Technical Writer in Australia');
INSERT INTO product (name, description) VALUES ('CHILL LUCK','A Lacklusture Epistle of a Boat And a Technical Writer who must Fight a A Shark in The Canadian Rockies');
INSERT INTO product (name, description) VALUES ('CHINATOWN GLADIATOR','A Brilliant Panorama of a Technical Writer And a Lumberjack who must Escape a Butler in Ancient India');
INSERT INTO product (name, description) VALUES ('CHISUM BEHAVIOR','A Epic Documentary of a Sumo Wrestler And a Butler who must Kill a Car in Ancient India');
INSERT INTO product (name, description) VALUES ('CHITTY LOCK','A Boring Epistle of a Boat And a Database Administrator who must Kill a Sumo Wrestler in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('CHOCOLAT HARRY','A Action-Packed Epistle of a Dentist And a Moose who must Meet a Mad Cow in Ancient Japan');
INSERT INTO product (name, description) VALUES ('CHOCOLATE DUCK','A Unbelieveable Story of a Mad Scientist And a Technical Writer who must Discover a Composer in Ancient China');
INSERT INTO product (name, description) VALUES ('CHRISTMAS MOONSHINE','A Action-Packed Epistle of a Feminist And a Astronaut who must Conquer a Boat in A Manhattan Penthouse');
INSERT INTO product (name, description) VALUES ('CIDER DESIRE','A Stunning Character Study of a Composer And a Mad Cow who must Succumb a Cat in Soviet Georgia');
INSERT INTO product (name, description) VALUES ('CINCINATTI WHISPERER','A Brilliant Saga of a Pastry Chef And a Hunter who must Confront a Butler in Berlin');
INSERT INTO product (name, description) VALUES ('CIRCUS YOUTH','A Thoughtful Drama of a Pastry Chef And a Dentist who must Pursue a Girl in A Baloon');
INSERT INTO product (name, description) VALUES ('CITIZEN SHREK','A Fanciful Character Study of a Technical Writer And a Husband who must Redeem a Robot in The Outback');
INSERT INTO product (name, description) VALUES ('CLASH FREDDY','A Amazing Yarn of a Composer And a Squirrel who must Escape a Astronaut in Australia');
INSERT INTO product (name, description) VALUES ('CLEOPATRA DEVIL','A Fanciful Documentary of a Crocodile And a Technical Writer who must Fight a A Shark in A Baloon');
INSERT INTO product (name, description) VALUES ('CLERKS ANGELS','A Thrilling Display of a Sumo Wrestler And a Girl who must Confront a Man in A Baloon');
INSERT INTO product (name, description) VALUES ('CLOCKWORK PARADISE','A Insightful Documentary of a Technical Writer And a Feminist who must Challenge a Cat in A Baloon');
INSERT INTO product (name, description) VALUES ('CLONES PINOCCHIO','A Amazing Drama of a Car And a Robot who must Pursue a Dentist in New Orleans');
INSERT INTO product (name, description) VALUES ('CLOSER BANG','A Unbelieveable Panorama of a Frisbee And a Hunter who must Vanquish a Monkey in Ancient India');
INSERT INTO product (name, description) VALUES ('CLUB GRAFFITI','A Epic Tale of a Pioneer And a Hunter who must Escape a Girl in A U-Boat');
INSERT INTO product (name, description) VALUES ('CLUE GRAIL','A Taut Tale of a Butler And a Mad Scientist who must Build a Crocodile in Ancient China');
INSERT INTO product (name, description) VALUES ('CLUELESS BUCKET','A Taut Tale of a Car And a Pioneer who must Conquer a Sumo Wrestler in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('CLYDE THEORY','A Beautiful Yarn of a Astronaut And a Frisbee who must Overcome a Explorer in A Jet Boat');
INSERT INTO product (name, description) VALUES ('COAST RAINBOW','A Astounding Documentary of a Mad Cow And a Pioneer who must Challenge a Butler in The Sahara Desert');
INSERT INTO product (name, description) VALUES ('COLDBLOODED DARLING','A Brilliant Panorama of a Dentist And a Moose who must Find a Student in The Gulf of Mexico');
INSERT INTO product (name, description) VALUES ('COLOR PHILADELPHIA','A Thoughtful Panorama of a Car And a Crocodile who must Sink a Monkey in The Sahara Desert');
INSERT INTO product (name, description) VALUES ('COMA HEAD','A Awe-Inspiring Drama of a Boy And a Frisbee who must Escape a Pastry Chef in California');
INSERT INTO product (name, description) VALUES ('COMANCHEROS ENEMY','A Boring Saga of a Lumberjack And a Monkey who must Find a Monkey in The Gulf of Mexico');
INSERT INTO product (name, description) VALUES ('COMFORTS RUSH','A Unbelieveable Panorama of a Pioneer And a Husband who must Meet a Mad Cow in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('COMMAND DARLING','A Awe-Inspiring Tale of a Forensic Psychologist And a Woman who must Challenge a Database Administrator in Ancient Japan');
INSERT INTO product (name, description) VALUES ('COMMANDMENTS EXPRESS','A Fanciful Saga of a Student And a Mad Scientist who must Battle a Hunter in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('CONEHEADS SMOOCHY','A Touching Story of a Womanizer And a Composer who must Pursue a Husband in Nigeria');
INSERT INTO product (name, description) VALUES ('CONFESSIONS MAGUIRE','A Insightful Story of a Car And a Boy who must Battle a Technical Writer in A Baloon');
INSERT INTO product (name, description) VALUES ('CONFIDENTIAL INTERVIEW','A Stunning Reflection of a Cat And a Woman who must Find a Astronaut in Ancient Japan');
INSERT INTO product (name, description) VALUES ('CONFUSED CANDLES','A Stunning Epistle of a Cat And a Forensic Psychologist who must Confront a Pioneer in A Baloon');
INSERT INTO product (name, description) VALUES ('CONGENIALITY QUEST','A Touching Documentary of a Cat And a Pastry Chef who must Find a Lumberjack in A Baloon');
INSERT INTO product (name, description) VALUES ('CONNECTICUT TRAMP','A Unbelieveable Drama of a Crocodile And a Mad Cow who must Reach a Dentist in A Shark Tank');
INSERT INTO product (name, description) VALUES ('CONNECTION MICROCOSMOS','A Fateful Documentary of a Crocodile And a Husband who must Face a Husband in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('CONQUERER NUTS','A Taut Drama of a Mad Scientist And a Man who must Escape a Pioneer in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('CONSPIRACY SPIRIT','A Awe-Inspiring Story of a Student And a Frisbee who must Conquer a Crocodile in An Abandoned Mine Shaft');
INSERT INTO product (name, description) VALUES ('CONTACT ANONYMOUS','A Insightful Display of a A Shark And a Monkey who must Face a Database Administrator in Ancient India');
INSERT INTO product (name, description) VALUES ('CONTROL ANTHEM','A Fateful Documentary of a Robot And a Student who must Battle a Cat in A Monastery');
INSERT INTO product (name, description) VALUES ('CONVERSATION DOWNHILL','A Taut Character Study of a Husband And a Waitress who must Sink a Squirrel in A MySQL Convention');
INSERT INTO product (name, description) VALUES ('CORE SUIT','A Unbelieveable Tale of a Car And a Explorer who must Confront a Boat in A Manhattan Penthouse');
INSERT INTO product (name, description) VALUES ('COWBOY DOOM','A Astounding Drama of a Boy And a Lumberjack who must Fight a Butler in A Baloon');
INSERT INTO product (name, description) VALUES ('CRAFT OUTFIELD','A Lacklusture Display of a Explorer And a Hunter who must Succumb a Database Administrator in A Baloon Factory');
INSERT INTO product (name, description) VALUES ('CRANES RESERVOIR','A Fanciful Documentary of a Teacher And a Dog who must Outgun a Forensic Psychologist in A Baloon Factory');
INSERT INTO product (name, description) VALUES ('CRAZY HOME','A Fanciful Panorama of a Boy And a Woman who must Vanquish a Database Administrator in The Outback');
INSERT INTO product (name, description) VALUES ('CREATURES SHAKESPEARE','A Emotional Drama of a Womanizer And a Squirrel who must Vanquish a Crocodile in Ancient India');
INSERT INTO product (name, description) VALUES ('CREEPERS KANE','A Awe-Inspiring Reflection of a Squirrel And a Boat who must Outrace a Car in A Jet Boat');
INSERT INTO product (name, description) VALUES ('CROOKED FROGMEN','A Unbelieveable Drama of a Hunter And a Database Administrator who must Battle a Crocodile in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('CROSSING DIVORCE','A Beautiful Documentary of a Dog And a Robot who must Redeem a Womanizer in Berlin');
INSERT INTO product (name, description) VALUES ('CROSSROADS CASUALTIES','A Intrepid Documentary of a Sumo Wrestler And a Astronaut who must Battle a Composer in The Outback');
INSERT INTO product (name, description) VALUES ('CROW GREASE','A Awe-Inspiring Documentary of a Woman And a Husband who must Sink a Database Administrator in The First Manned Space Station');
INSERT INTO product (name, description) VALUES ('CROWDS TELEMARK','A Intrepid Documentary of a Astronaut And a Forensic Psychologist who must Find a Frisbee in An Abandoned Fun House');
INSERT INTO product (name, description) VALUES ('CRUELTY UNFORGIVEN','A Brilliant Tale of a Car And a Moose who must Battle a Dentist in Nigeria');
INSERT INTO product (name, description) VALUES ('CRUSADE HONEY','A Fast-Paced Reflection of a Explorer And a Butler who must Battle a Madman in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('CRYSTAL BREAKING','A Fast-Paced Character Study of a Feminist And a Explorer who must Face a Pastry Chef in Ancient Japan');
INSERT INTO product (name, description) VALUES ('CUPBOARD SINNERS','A Emotional Reflection of a Frisbee And a Boat who must Reach a Pastry Chef in An Abandoned Amusement Park');
INSERT INTO product (name, description) VALUES ('CURTAIN VIDEOTAPE','A Boring Reflection of a Dentist And a Mad Cow who must Chase a Secret Agent in A Shark Tank');

INSERT INTO shop_product (shop_id, product_id) VALUES (1,83);
INSERT INTO shop_product (shop_id, product_id) VALUES (1,82);
INSERT INTO shop_product (shop_id, product_id) VALUES (1,90);
INSERT INTO shop_product (shop_id, product_id) VALUES (1,61);
INSERT INTO shop_product (shop_id, product_id) VALUES (1,42);
INSERT INTO shop_product (shop_id, product_id) VALUES (1,54);
INSERT INTO shop_product (shop_id, product_id) VALUES (1,100);
INSERT INTO shop_product (shop_id, product_id) VALUES (2,101);
INSERT INTO shop_product (shop_id, product_id) VALUES (2,129);
INSERT INTO shop_product (shop_id, product_id) VALUES (2,198);
INSERT INTO shop_product (shop_id, product_id) VALUES (3,21);
INSERT INTO shop_product (shop_id, product_id) VALUES (3,23);
INSERT INTO shop_product (shop_id, product_id) VALUES (3,27);
INSERT INTO shop_product (shop_id, product_id) VALUES (3,29);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,33);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,37);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,38);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,39);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,39);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,40);
INSERT INTO shop_product (shop_id, product_id) VALUES (4,41);
INSERT INTO shop_product (shop_id, product_id) VALUES (5,42);
INSERT INTO shop_product (shop_id, product_id) VALUES (5,44);
INSERT INTO shop_product (shop_id, product_id) VALUES (5,45);
INSERT INTO shop_product (shop_id, product_id) VALUES (6,46);
INSERT INTO shop_product (shop_id, product_id) VALUES (6,68);
INSERT INTO shop_product (shop_id, product_id) VALUES (6,70);
INSERT INTO shop_product (shop_id, product_id) VALUES (6,71);
INSERT INTO shop_product (shop_id, product_id) VALUES (6,95);
INSERT INTO shop_product (shop_id, product_id) VALUES (6,98);
INSERT INTO shop_product (shop_id, product_id) VALUES (7,98);
INSERT INTO shop_product (shop_id, product_id) VALUES (7,99);
INSERT INTO shop_product (shop_id, product_id) VALUES (7,73);
INSERT INTO shop_product (shop_id, product_id) VALUES (7,134);
INSERT INTO shop_product (shop_id, product_id) VALUES (7,167);
INSERT INTO shop_product (shop_id, product_id) VALUES (8,20);
INSERT INTO shop_product (shop_id, product_id) VALUES (8,22);
INSERT INTO shop_product (shop_id, product_id) VALUES (8,24);
INSERT INTO shop_product (shop_id, product_id) VALUES (8,24);
INSERT INTO shop_product (shop_id, product_id) VALUES (9,27);
INSERT INTO shop_product (shop_id, product_id) VALUES (9,39);
INSERT INTO shop_product (shop_id, product_id) VALUES (9,51);
INSERT INTO shop_product (shop_id, product_id) VALUES (9,63);
INSERT INTO shop_product (shop_id, product_id) VALUES (9,76);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,78);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,80);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,89);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,93);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,94);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,94);
INSERT INTO shop_product (shop_id, product_id) VALUES (10,98);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,3);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,10);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,37);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,87);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,88);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,124);
INSERT INTO shop_product (shop_id, product_id) VALUES (11,197);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,28);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,29);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,37);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,33);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,35);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,44);
INSERT INTO shop_product (shop_id, product_id) VALUES (12,46);
INSERT INTO shop_product (shop_id, product_id) VALUES (13,47);
INSERT INTO shop_product (shop_id, product_id) VALUES (13,50);
INSERT INTO shop_product (shop_id, product_id) VALUES (13,54);
INSERT INTO shop_product (shop_id, product_id) VALUES (13,55);
INSERT INTO shop_product (shop_id, product_id) VALUES (15,56);
INSERT INTO shop_product (shop_id, product_id) VALUES (15,57);
INSERT INTO shop_product (shop_id, product_id) VALUES (15,59);
INSERT INTO shop_product (shop_id, product_id) VALUES (15,61);
INSERT INTO shop_product (shop_id, product_id) VALUES (15,64);
INSERT INTO shop_product (shop_id, product_id) VALUES (15,69);
INSERT INTO shop_product (shop_id, product_id) VALUES (16,83);
INSERT INTO shop_product (shop_id, product_id) VALUES (16,85);
INSERT INTO shop_product (shop_id, product_id) VALUES (16,86);
INSERT INTO shop_product (shop_id, product_id) VALUES (16,92);
INSERT INTO shop_product (shop_id, product_id) VALUES (17,92);
INSERT INTO shop_product (shop_id, product_id) VALUES (17,98);
INSERT INTO shop_product (shop_id, product_id) VALUES (17,39);
INSERT INTO shop_product (shop_id, product_id) VALUES (17,46);
INSERT INTO shop_product (shop_id, product_id) VALUES (17,97);
INSERT INTO shop_product (shop_id, product_id) VALUES (17,106);
INSERT INTO shop_product (shop_id, product_id) VALUES (18,117);
INSERT INTO shop_product (shop_id, product_id) VALUES (18,125);
INSERT INTO shop_product (shop_id, product_id) VALUES (18,158);
INSERT INTO shop_product (shop_id, product_id) VALUES (18,27);
INSERT INTO shop_product (shop_id, product_id) VALUES (18,30);
INSERT INTO shop_product (shop_id, product_id) VALUES (18,33);
INSERT INTO shop_product (shop_id, product_id) VALUES (19,34);
INSERT INTO shop_product (shop_id, product_id) VALUES (19,37);
INSERT INTO shop_product (shop_id, product_id) VALUES (19,39);
INSERT INTO shop_product (shop_id, product_id) VALUES (19,47);
INSERT INTO shop_product (shop_id, product_id) VALUES (19,47);
INSERT INTO shop_product (shop_id, product_id) VALUES (19,47);
INSERT INTO shop_product (shop_id, product_id) VALUES (20,49);
INSERT INTO shop_product (shop_id, product_id) VALUES (20,49);
INSERT INTO shop_product (shop_id, product_id) VALUES (20,51);
INSERT INTO shop_product (shop_id, product_id) VALUES (21,51);
INSERT INTO shop_product (shop_id, product_id) VALUES (21,54);
INSERT INTO shop_product (shop_id, product_id) VALUES (21,55);
INSERT INTO shop_product (shop_id, product_id) VALUES (21,57);
INSERT INTO shop_product (shop_id, product_id) VALUES (21,57);
INSERT INTO shop_product (shop_id, product_id) VALUES (21,61);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,65);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,68);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,69);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,71);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,73);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,85);
INSERT INTO shop_product (shop_id, product_id) VALUES (22,93);
INSERT INTO shop_product (shop_id, product_id) VALUES (23,95);
INSERT INTO shop_product (shop_id, product_id) VALUES (23,96);
INSERT INTO shop_product (shop_id, product_id) VALUES (23,55);
INSERT INTO shop_product (shop_id, product_id) VALUES (23,143);
INSERT INTO shop_product (shop_id, product_id) VALUES (23,20);
INSERT INTO shop_product (shop_id, product_id) VALUES (24,22);
INSERT INTO shop_product (shop_id, product_id) VALUES (24,22);
INSERT INTO shop_product (shop_id, product_id) VALUES (24,23);
INSERT INTO shop_product (shop_id, product_id) VALUES (24,28);
INSERT INTO shop_product (shop_id, product_id) VALUES (25,30);
INSERT INTO shop_product (shop_id, product_id) VALUES (25,34);
INSERT INTO shop_product (shop_id, product_id) VALUES (25,35);
INSERT INTO shop_product (shop_id, product_id) VALUES (25,36);
INSERT INTO shop_product (shop_id, product_id) VALUES (25,37);
INSERT INTO shop_product (shop_id, product_id) VALUES (25,42);
INSERT INTO shop_product (shop_id, product_id) VALUES (26,43);
INSERT INTO shop_product (shop_id, product_id) VALUES (26,55);
INSERT INTO shop_product (shop_id, product_id) VALUES (26,60);
INSERT INTO shop_product (shop_id, product_id) VALUES (26,67);
INSERT INTO shop_product (shop_id, product_id) VALUES (26,69);
INSERT INTO shop_product (shop_id, product_id) VALUES (27,70);
INSERT INTO shop_product (shop_id, product_id) VALUES (27,72);
INSERT INTO shop_product (shop_id, product_id) VALUES (27,76);
INSERT INTO shop_product (shop_id, product_id) VALUES (27,79);
INSERT INTO shop_product (shop_id, product_id) VALUES (28,82);
INSERT INTO shop_product (shop_id, product_id) VALUES (28,87);
INSERT INTO shop_product (shop_id, product_id) VALUES (28,90);
INSERT INTO shop_product (shop_id, product_id) VALUES (29,91);
INSERT INTO shop_product (shop_id, product_id) VALUES (29,92);
INSERT INTO shop_product (shop_id, product_id) VALUES (30,95);
INSERT INTO shop_product (shop_id, product_id) VALUES (30,95);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,96);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,99);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,24);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,57);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,67);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,144);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,24);
INSERT INTO shop_product (shop_id, product_id) VALUES (31,24);
INSERT INTO shop_product (shop_id, product_id) VALUES (32,25);
INSERT INTO shop_product (shop_id, product_id) VALUES (32,40);
INSERT INTO shop_product (shop_id, product_id) VALUES (34,47);
INSERT INTO shop_product (shop_id, product_id) VALUES (34,49);
INSERT INTO shop_product (shop_id, product_id) VALUES (34,51);
INSERT INTO shop_product (shop_id, product_id) VALUES (34,57);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,60);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,72);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,72);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,73);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,76);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,86);
INSERT INTO shop_product (shop_id, product_id) VALUES (35,87);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,91);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,94);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,97);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,98);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,97);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,45);
INSERT INTO shop_product (shop_id, product_id) VALUES (37,133);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,161);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,20);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,21);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,21);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,25);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,29);
INSERT INTO shop_product (shop_id, product_id) VALUES (39,31);
INSERT INTO shop_product (shop_id, product_id) VALUES (40,32);
INSERT INTO shop_product (shop_id, product_id) VALUES (40,33);
INSERT INTO shop_product (shop_id, product_id) VALUES (40,34);
INSERT INTO shop_product (shop_id, product_id) VALUES (40,35);
INSERT INTO shop_product (shop_id, product_id) VALUES (42,37);
INSERT INTO shop_product (shop_id, product_id) VALUES (42,38);
INSERT INTO shop_product (shop_id, product_id) VALUES (42,38);
INSERT INTO shop_product (shop_id, product_id) VALUES (42,39);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,43);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,49);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,60);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,65);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,67);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,70);
INSERT INTO shop_product (shop_id, product_id) VALUES (43,74);
INSERT INTO shop_product (shop_id, product_id) VALUES (44,83);
INSERT INTO shop_product (shop_id, product_id) VALUES (44,83);
INSERT INTO shop_product (shop_id, product_id) VALUES (44,84);
INSERT INTO shop_product (shop_id, product_id) VALUES (44,97);
INSERT INTO shop_product (shop_id, product_id) VALUES (44,15);
INSERT INTO shop_product (shop_id, product_id) VALUES (45,88);